const items = [
  { id: 1, name: "Bolo de chocolate", quantity: 1, total: 5 },
  { id: 2, name: "Bolo de milho", quantity: 1, total: 5 },
  {
    id: 3,
    name: "Bolo de cenoura com cobertura de chocolate",
    quantity: 1,
    total: 5,
  },
  { id: 4, name: "Bolo de coco", quantity: 1, total: 5 },
  { id: 5, name: "Bolo de churros", quantity: 1, total: 5 },
  { id: 6, name: "Pingo de leite", quantity: 1, total: 5 },
  { id: 7, name: "Suspiro", quantity: 1, total: 5 },
  { id: 8, name: "Maria Mole coberta de chocolate", quantity: 1, total: 5 },
  { id: 9, name: "Maria mole", quantity: 1, total: 5 },
  { id: 10, name: "Bananinha", quantity: 1, total: 5 },
  { id: 11, name: "Cocada", quantity: 1, total: 5 },
  { id: 12, name: "Arroz doce", quantity: 1, total: 5 },
  { id: 13, name: "Canjica", quantity: 1, total: 5 },
  { id: 14, name: "Sagu", quantity: 1, total: 5 },
  { id: 15, name: "Doce de abóbora", quantity: 1, total: 5 },
  { id: 16, name: "Doce de batata doce", quantity: 1, total: 5 },
  { id: 17, name: "Doce de leite", quantity: 1, total: 5 },
  { id: 18, name: "Torta de frango", quantity: 1, total: 5 },
  { id: 19, name: "Torta de palmito", quantity: 1, total: 5 },
  { id: 20, name: "Cuscuz", quantity: 1, total: 5 },
  { id: 21, name: "Calabresa", quantity: 3, total: 10 },
  { id: 22, name: "Cebolas", quantity: 15, total: 20 },
  { id: 23, name: "Bacon", quantity: 3, total: 10 },
  { id: 24, name: "Feijão preto", quantity: 2, total: 10 },
  { id: 25, name: "Costelinha de porco", quantity: 3, total: 10 },
  { id: 26, name: "Pães francês", quantity: 60, total: 100 },
  { id: 27, name: "Vinho tinto suave de mesa", quantity: 10, total: 20 },
  { id: 28, name: "Salsicha", quantity: 4, total: 10 },
  { id: 29, name: "Pães de hot dog", quantity: 80, total: 100 },
  { id: 30, name: "Batata palha", quantity: 1, total: 5 },
  { id: 31, name: "Tomates", quantity: 10, total: 20 },
  { id: 32, name: "Maionese", quantity: 1, total: 5 },
  { id: 33, name: "Colheres", quantity: 300, total: 500 },
  { id: 34, name: "Copos descartáveis", quantity: 4, total: 10 },
  { id: 35, name: "Potes descartáveis", quantity: 300, total: 500 },
];

export default items;
